### ISSUE TITLE
Scripting Format

### ISSUE THREAD

**Issue by crichID** [codefoster/gh-ms-mva#1]
@codefoster thank you for creating this repo as a place where we can collaborate. The outline looks great and will give us a strong start in creating content.

I would also like to loop in @brianamarie who is one of my colleagues here on the training team and very interested in helping with this project.

As we move forward with next steps, we have a couple of questions:
- do you have a standard format or structure for the more detailed content?
- how tightly scripted are the on-camera conversations? My understanding from our conversation is that we would prepare a list of questions and the answers would be unscripted, but prepared. Is that correct?

Thank you in advance!

**Comment by codefoster** [comment]
Thanks, Cynthia.
- _do we have a standard format..._
  On the general content structure, we have 6 modules and each has roughly 5 10-minute clips. That's pretty rough. Clips can vary from 10 min by quite a bit. Within a clip, we will walk the viewers through concepts using slides OR we'll show them a demo. Within this general framework, there's a lot of creative freedom for how a presenter decides to relay the concepts. One thing to keep in mind is that we have to be rather strict about not showing copyrighted material on screen, so when we use images in our slides, we be sure they are attributed correctly
- _how tightly scripted..._
  Not really scripted at all. For any given clip, likely a single presenter will be delivering the content, but the co-presenter will feel free to ask questions to help clarify, help steer the content, help add substance to a thin topic, or even to cut off a thick one.
