### ISSUE TITLE
Notes from call 8/2

### ISSUE THREAD

**Issue by brianamarie** [codefoster/gh-ms-mva#5]
#### General notes
- How much should be in slides? 
  - Up to me, it oculd be very simple placeholders with a few points then break away to a demo 👍 
  - Helper slides bring in clips to show things instead of having to cut away and find a browser 
  - Include DEMO slides to remind presenter when to jump into demp
#### Module 1
- Include GitHub for more than just code (show wedding planning?) 
  - Recipes 
- Audience is Microsoft developers on TFS who are resisting the Git movement
- They've used it THROUGH visual studio, but anything outside of integration gets unfamilliar
- General concept of distributed vs centeralized 
- snapshots vs deltas 
- What functions specifically are GitHub?
  - Issues
  - Pull Requests
  - Orgs and teams
  - code review 
  - Integrations are GitHub specific (azure website will go straight to GitHub and continuously deploy, but not if it's just on Git. Azure also has ability to set up GitHub repo in Azure so you can use vanilla Git. 
- Jump to VSCode or other Microsoft open source 
- Have in mind parts that are essential to get across, because banter may become more important 
- Combine category 1 & 2 (Background & introductions, Microsoft & GitHub)
#### Module 2
- If there's no open source license on a repository, what is it? 
- How many repos don't have licenses? 
- If you created an org, gave someone else owner access, can you remove yourself from it? 
- Fork and pull vs. GitHub flow 
- Everything is still in the cloud 
- Add in something with showing visuals for graphs, look at some Microsoft open source data
#### Module 3
- Briana to chime throughout in parallels between browser and CLI 
- Worth mentioning that you can use other diffs 
#### Module 5
- focus on power and speed 
- Mention that clone your own, you can also clone other repositories 
- Move config section to Module 6, demo there
- find image of workflow with commands cheat sheet
- Discuss how pull is fetch/merge 
- Move danger zone to module 6
- git diff 
- git diftool -d (Jeremy will talk about) 
#### Module 6
- Multiple remotes for fork and pull workflow? 
- Origin and Azure & multiple remotes 
- Maybe talk about remote tracking branches 
- Difference between reset and rm
- git add is 4+ 
### Next steps
- Meet again tomorrow to practice workflow in step 2 
- Practice cloning locally to GH desktop in module 3, opening PR in desktop and showing in browser
- Q: Git Bash?

**Comment by githubteacher** [comment]
@codefoster 👋 Can you please add this account as a collaborator?
